---
gitlabinstance:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/credentials"
  additionalProperties: false
credentials:
  type: "object"
  properties:
    url:
      description: "Username and domain for the WinRM connection (example: ad_user@domain.tld)."
      type: "string"
      required: true
    token:
      description: The token used to authenticate to the Gitlab server
      type: "string"
      secret: true
      required: true
    verify_ssl:
      description: Whether to verify the SSL certificate when connecting to the Gitlab server
      type: "boolean"
      required: false
  additionalProperties: false